// AUTO-GENERATED by scripts/gen-version.ts — do not edit by hand.
// Source of truth: package.json "version". Regenerated on every build
// (prebuild). See #57 — keeps SURFACE_RENDER_VERSION from drifting.
export const SURFACE_RENDER_VERSION = "0.3.0";
