// AUTO-GENERATED by scripts/gen-version.ts — do not edit by hand.
// Source of truth: package.json "version". Regenerated on every build
// (prebuild). Mirrors surface-client's #57 — keeps ACCOUNT_CLIENT_VERSION
// from drifting.
export const ACCOUNT_CLIENT_VERSION = "0.1.0";
