// AUTO-GENERATED by scripts/gen-version.ts — do not edit by hand.
// Source of truth: package.json "version". Regenerated on every build
// (prebuild). Mirrors account-client / surface-client #57 — keeps
// PARACHUTE_MCP_VERSION from drifting.
export const PARACHUTE_MCP_VERSION = "0.1.0";
