#!/usr/bin/env bun
/**
 * Codegen: emit `src/version.ts` from `package.json`'s `version`, so the
 * exported `ACCOUNT_CLIENT_VERSION` constant can NEVER drift from the version
 * the package actually ships at.
 *
 * Runs in `prebuild` (and therefore in `prepare` / `prepublishOnly` → `build`),
 * so the published bundle's version constant is always regenerated from the
 * source of truth at publish time. Mirrors surface-client's gen-version (#57):
 * a hand-maintained constant will stall behind the shipped version, so we
 * generate it and a unit test (`version.test.ts`) guards the committed copy.
 */
const pkgUrl = new URL("../package.json", import.meta.url);
const pkg = (await Bun.file(pkgUrl).json()) as { version: string };

const out = `// AUTO-GENERATED by scripts/gen-version.ts — do not edit by hand.
// Source of truth: package.json "version". Regenerated on every build
// (prebuild). Mirrors surface-client's #57 — keeps ACCOUNT_CLIENT_VERSION
// from drifting.
export const ACCOUNT_CLIENT_VERSION = ${JSON.stringify(pkg.version)};
`;

const target = new URL("../src/version.ts", import.meta.url);
await Bun.write(target, out);
console.log(`gen-version: wrote src/version.ts (${pkg.version})`);
