#!/usr/bin/env bun
/**
 * Codegen: emit `src/version.ts` from `package.json`'s `version`, so the
 * exported `SURFACE_RENDER_VERSION` constant can NEVER drift from the version
 * the package actually ships at.
 *
 * Runs in `prebuild` (and therefore in `prepare` / `prepublishOnly` → `build`),
 * so the published bundle's version constant is always regenerated from the
 * source of truth at publish time. Mirrors surface-client's guard (see #57). A
 * unit test (`version.test.ts`) guards the committed copy so a stale commit
 * between bump and build also fails CI.
 */
const pkgUrl = new URL("../package.json", import.meta.url);
const pkg = (await Bun.file(pkgUrl).json()) as { version: string };

const out = `// AUTO-GENERATED by scripts/gen-version.ts — do not edit by hand.
// Source of truth: package.json "version". Regenerated on every build
// (prebuild). See #57 — keeps SURFACE_RENDER_VERSION from drifting.
export const SURFACE_RENDER_VERSION = ${JSON.stringify(pkg.version)};
`;

const target = new URL("../src/version.ts", import.meta.url);
await Bun.write(target, out);
console.log(`gen-version: wrote src/version.ts (${pkg.version})`);
