// AUTO-GENERATED by scripts/gen-version.ts — do not edit by hand.
// Source of truth: package.json "version". Regenerated on every build
// (prebuild). See #57 — keeps SURFACE_CLIENT_VERSION from drifting.
export const SURFACE_CLIENT_VERSION = "0.3.2";
